### PR TITLE
Issue #4 Replace Single w/ First

### PR DESCRIPTION
**Pull request by bradtwurst**
one way of handling the exception, not sure if it is the best way.

### CODE REVIEW

**Comment by kswoll** [comment]
Thanks, I hadn't considered the possibility of multiple versions of the reactiveui assembly being present.  Your fixes look good to me!

**Comment by kswoll** [comment]
(I'll make a new nuget build tonight when I get back home.)

**Comment by fvermeulen** [comment]
@kswoll Do you created a new package?

**Comment by kswoll** [comment]
Whoops, apologies! It's been updated now.

**Comment by fvermeulen** [comment]
:+1: Thanks

**Pull request merged**
