### PR TITLE
Fixed references

### PR DESCRIPTION
**Pull request by butlerpeter**
Fix the references to ReactiveUI 7.0.0

### CODE REVIEW

**Comment by kswoll** [comment]
Thanks was working on this yesterday, but didn't have time to finish it up. Let's merge it and see what happens! :)

**Comment by kswoll** [comment]
FYI:  https://www.nuget.org/packages/ReactiveUI.Fody/2.0.65

**Comment by butlerpeter** [comment]
Wow that was fast :)

**Comment by kswoll** [comment]
You caught me at a good time. :)

**Comment by butlerpeter** [comment]
Updated nuget package works fine for me

**Pull request merged**
